name: Integration
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checking code
      uses: actions/checkout@v1

    - name: Integrating
      run: npm ci

    - name: Testing
      run: npm test

    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Releasing
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN:        ${{ secrets.NPM_TOKEN }}

    - name: Build documentation
      uses: andstor/jsdoc-action@v1
      with:
        source_dir:       ./source
        output_dir:       ./dist/docs
        config_file:      jsdoc.json
        template_name:    docdash
        front_page:       README.md

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:     ${{ secrets.GITHUB_TOKEN }}
        publish_dir:      ./dist/docs
